#!/bin/bash
# Extremely cheap imitation of Terminator theme opening beats
# Written by Yu-Jie Lin in 2016
# Public domain, or via UNLICENSE if not applicable.

wf=trapezium
freq=200-40
THUMPS=(
  "|sox -n -p synth 0.100 $wf $freq pad 0.050@0.100"
  "|sox -n -p synth 0.250 $wf $freq pad 0.050@0.250"
  "|sox -n -p synth 0.250 $wf $freq pad 0.050@0.250"
  "|sox -n -p synth 0.100 $wf $freq pad 0.050@0.100"
  "|sox -n -p synth 0.500 $wf $freq pad 0.500@0.500"
)

sox \
  "|sox -n -p synth 1.000 sin 0" \
  "${THUMPS[@]}" \
  "${THUMPS[@]}" \
  "${THUMPS[@]}" \
  "${THUMPS[@]}" \
  thumps.wav
